
// Some enum values could not be inserted automatically
// Compile and run this program with g++ and it will generate
// the missing constants to paste into irrlicht.bmx

#include <cstdio>
#include "include/irrlicht.h"

#define SHOWC(N) printf("Const " #N ":Int = %d\n", N);

using namespace irr;
using namespace scene;
using namespace io;
using namespace quake3;

int main() {
  SHOWC(EDS_BBOX_ALL);
  SHOWC(EMWT_IRR_MESH);
  SHOWC(EMWT_COLLADA);
  SHOWC(EMWT_STL);
  SHOWC(EMWT_OBJ);
  SHOWC(EMWT_PLY);
  SHOWC(ESNT_SCENE_MANAGER);
  SHOWC(ESNT_CUBE);
  SHOWC(ESNT_SPHERE);
  SHOWC(ESNT_TEXT);
  SHOWC(ESNT_WATER_SURFACE);
  SHOWC(ESNT_TERRAIN);
  SHOWC(ESNT_SKY_BOX);
  SHOWC(ESNT_SKY_DOME);
  SHOWC(ESNT_SHADOW_VOLUME);
  SHOWC(ESNT_OCTREE);
  SHOWC(ESNT_MESH);
  SHOWC(ESNT_LIGHT);
  SHOWC(ESNT_EMPTY);
  SHOWC(ESNT_DUMMY_TRANSFORMATION);
  SHOWC(ESNT_CAMERA);
  SHOWC(ESNT_BILLBOARD);
  SHOWC(ESNT_ANIMATED_MESH);
  SHOWC(ESNT_PARTICLE_SYSTEM);
  SHOWC(ESNT_Q3SHADER_SCENE_NODE);
  SHOWC(ESNT_MD3_SCENE_NODE);
  SHOWC(ESNT_VOLUME_LIGHT);
  SHOWC(ESNT_CAMERA_MAYA);
  SHOWC(ESNT_CAMERA_FPS);
  SHOWC(ESNT_UNKNOWN);
  SHOWC(ESNT_ANY);
  SHOWC(EFAT_ZIP);
  SHOWC(EFAT_GZIP);
  SHOWC(EFAT_FOLDER);
  SHOWC(EFAT_PAK);
  SHOWC(EFAT_NPK);
  SHOWC(EFAT_TAR);
  SHOWC(EFAT_WAD);
  SHOWC(EFAT_UNKNOWN);
  SHOWC(SCROLL);
  SHOWC(SCALE);
  SHOWC(ROTATE);
  SHOWC(STRETCH);
  SHOWC(TURBULENCE);
  SHOWC(WAVE);
  SHOWC(IDENTITY);
  SHOWC(VERTEX);
  SHOWC(TEXTURE);
  SHOWC(LIGHTMAP);
  SHOWC(ENVIRONMENT);
  SHOWC(DOLLAR_LIGHTMAP);
  SHOWC(BULGE);
  SHOWC(AUTOSPRITE);
  SHOWC(AUTOSPRITE2);
  SHOWC(TRANSFORM);
  SHOWC(EXACTVERTEX);
  SHOWC(CONSTANT);
  SHOWC(LIGHTINGSPECULAR);
  SHOWC(MOVE);
  SHOWC(NORMAL);
  SHOWC(IDENTITYLIGHTING);
  SHOWC(SINUS);
  SHOWC(COSINUS);
  SHOWC(SQUARE);
  SHOWC(TRIANGLE);
  SHOWC(SAWTOOTH);
  SHOWC(SAWTOOTH_INVERSE);
  SHOWC(NOISE);
  return 0;
}

